### ISSUE TITLE
新增搜索 无效

### ISSUE THREAD

**Issue by okerivy** [eallion/favorite#2]
添加个搜索， 但是无法运行，原版是可以的，你的3月31号之前代码也是可以的，
 添加代码如下
`<li data-type="jingdong" class="search-item jingdong">京东</li>`

`{ url: 'http://search.jd.com/Search?keyword=', type: 'jingdong' },`

麻烦给看下，谢谢

**Comment by eallion** [comment]
@okerivy 
已经修改。
现在应该可以用了。

需要同时在 `static/css/style.css` 里：
160行位置添加样式。
<https://github.com/eallion/favorite/commit/ed1df616e97d4cffff51213ea3adfad75db66790#diff-a16a51aaea7dc21d3202074fc7228024>

**Comment by eallion** [comment]
不能运行的原因是 js 用了 CDN ，`{ url: 'http://search.jd.com/Search?keyword=', type: 'jingdong' },` 没有在CDN上刷新。

**Comment by okerivy** [comment]
谢谢，正常了 ：）
